---
- name: Configure LLDP
  hosts: all_routers
  gather_facts: false
  vars:
    lldp_state: >-
      {{ 'deleted' if not services.lldp.enabled | default(false) else 'merged' }}

  tasks:
    - name: Enable LLDP Service
      # <TODO> - Specify an Ansible module to configure global LLDP state
        # <TODO> - Specify LLDP global parameters
        state: # <TODO> - Use a variable to define the desired state

    - name: Enable LLDP on interfaces
      cisco.ios.ios_lldp_interfaces:
        config:
          - name: # <TODO> - Use a variable to specify the interface name
            # <TODO> - Specify interface LLDP rx/tx state
        state: "{{ interface_lldp_state }}"
      loop: "{{ host_interfaces }}"
      loop_control:
        label: # <TODO> - Create a custom label for each loop iteration
      vars:
        interface_dict: "{{ lookup('ansible.builtin.dict', item) }}"
        interface_lldp_state: # <TODO> - Create a task variable to define the state
