---
- name: Configure NTP
  hosts: all_routers
  gather_facts: false
  vars:
    ntp_state: >-
      {{ 'deleted' if not services.ntp.enabled | default(false) else 'merged' }}

  tasks:
    - name: Configure NTP Source Interface
      # <TODO> - Use an Ansible module to configure NTP
        config:
          source: # <TODO> - Use a variable to specify the source interface
        state: # <TODO> - Use a play variable to define the NTP state
      when: # <TODO> - Specify the conditional statement and use a default filter

    - name: Configure NTP Servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: # <TODO> - Use a variable and a filter for the NTP servers
        state: "{{ ntp_state }}"
      loop: "{{ ntp.servers }}"  # <TODO> - Use a filter to set a default value

    - name: Configure NTP Peers
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - # <TODO> - Specify parameter and use a variable to define peers
        state: "{{ ntp_state }}"
      loop: # <TODO> - Specify variable for iteration and use a default filter
      loop_control:
        loop_var: current_peer
        label: "Configuring peer '{{ current_peer }}'"
