---
all:
  hosts:
    inet-rtr1:
      ansible_host: # <TODO> Add IP Address 
    inet-rtr2:
      ansible_host: # <TODO> Add IP Address 
  vars:
    ansible_user:  # <TODO> Use vault variable to set API username
    ansible_password:  # <TODO> Use vault variable to set API password
  children:
    all_routers:
      hosts:
        inet_routers:
    inet_routers:
      hosts:
        # <TODO> Add inet routers
