---
all:
  hosts:
    inet-rtr1:
      ansible_host: # <TODO> - Specify management address
    inet-rtr2:
      ansible_host: # <TODO> - Specify management address
  children:
    inet_routers:
      hosts:
        inet-rtr1:
        # <TODO> - Add inet-rtr2 to group
    all_routers:
      children:
        # <TODO> - Add inet_routers to group
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: # <TODO> - Specify Network OS for connection
        ansible_network_cli_ssh_type: libssh
        ansible_user: # <TODO> - Specify username using a variable from the vault
        ansible_password: # <TODO> - Specify password using a variable from the vault
