---
- name: Validate IOS Configuration changes
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Diff Against Startup
      cisco.ios.ios_config:
        diff_against: <TODO Specify startup config>
