---
services:
  restconf:
    enabled: true
  ntp:
    source: # <TODO> Set Loopback source
  netconf:
    enabled: # <TODO> Enabled true
    features:
      - "candidate-datastore"
      - "side-effect-sync"
  lldp:
    enabled: true