---
# - name: Copy Run Start
#   hosts: all_routers
#   gather_facts: <TODO - Do Not Gather Facts
#   tasks:
#     - name: Copy Run Start
#       <TODO - use the ios_command module>:
#         commands: 
#           <TODO - Command to write memory>
