---
- name: Gather Built In Facts
  hosts: all_routers
  gather_facts: True
  tasks:
    - name: Display All Built In Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Display IOS Version
      ansible.builtin.debug:
        msg: "{{ ansible_facts['net_version'] }}"        

    - name: Gather IOS Facts with Cisco module
      cisco.ios.ios_facts:
        gather_subset: all
      register: ios_facts_results
    
    - name: Display Cisco IOS Facts
      ansible.builtin.debug:
        var: ios_facts_results