---
- name: Configure NTP Source Interface
  hosts: all_routers
  gather_facts: false
  tasks:
    - name: Configure NTP Source Interface
      cisco.ios.ios_ntp_global:
        config:
          source: "{{ services.ntp.source }}"

    - name: Configure NTP Servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: "{{ item }}"
      with_items: "{{ ntp.servers }}"

    - name: Configure NTP Peers
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: "{{ item }}"
              prefer: true
      with_items: "{{ ntp.peers }}"
