---
all:
  hosts:
    inet-rtr1:
      ansible_host: 192.168.10.10
    inet-rtr2:
      ansible_host: 192.168.10.11
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_password: "{{ vault_ansible_password }}"
  children:
    all_routers:
      hosts:
        inet_routers:
    inet_routers:
      hosts:
        inet-rtr1:
        inet-rtr2: