---
- name: Enable various services using IOS CONFIG
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Enable RESTCONF
      cisco.ios.ios_config:
        lines:
          - ip http secure-server
          - restconf
      when: services.restconf.enabled

    - name: Enable NETCONF
      cisco.ios.ios_config:
        lines:
          - netconf-yang
          - netconf-yang feature {{ item }}
      when: services.netconf.enabled
      with_items: "{{ services.netconf.features }}"

