---
- name: Gather Built In Facts
  hosts: all_routers
  gather_facts: True
  tasks:
    - name: Display All Built In Facts
      debug:
        msg: "{{ ansible_facts }}"

    - name: Display IOS Version
      debug:
        msg: "{{ ansible_facts['net_version'] }}"        

    - name: Gather IOS Facts with Cisco module
      cisco.ios.ios_facts:
        gather_subset: all
      register: ios_facts_results
    
    - name: Display Cisco IOS Facts
      debug:
        var: ios_facts_results

- name: Configure NTP Source Interface
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Configure NTP Source Interface
      cisco.ios.ios_ntp_global:
        config:
          source: "{{ services.ntp.source }}"

- name: Configure NTP Servers
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Configure NTP Servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: "{{ item }}"
      with_items: "{{ ntp.servers }}"

- name: Configure NTP Peers
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Configure NTP Peers
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: "{{ item }}"
              prefer: true
      with_items: "{{ ntp.peers }}"

- name: Enable LLDP
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Enable LLDP Service
      cisco.ios.ios_lldp:
        state: present
    
    - name: Enable LLDP on interfaces
      cisco.ios.ios_lldp_interfaces:
        config:
          - name: GigabitEthernet1
            receive: true
            transmit: true
          - name: GigabitEthernet2
            receive: true
            transmit: true
          - name: GigabitEthernet3
            receive: true
            transmit: true
          - name: GigabitEthernet4
            receive: true
            transmit: true
          - name: GigabitEthernet5
            receive: true
            transmit: true

- name: Enable various services using IOS CONFIG
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Enable RESTCONF
      cisco.ios.ios_config:
        lines:
          - ip http secure-server
          - restconf
      when: services.restconf.enabled

    - name: Enable NETCONF
      cisco.ios.ios_config:
        lines:
          - netconf-yang
          - netconf-yang feature {{ item }}
      when: services.netconf.enabled
      with_items: "{{ services.netconf.features }}"

- name: Copy Run Start
  hosts: all_routers
  gather_facts: False
  tasks:
    - name: Copy Run Start
      cisco.ios.ios_command:
        commands: 
          - command: write mem