---
- name: Configure NTP
  hosts: all_routers
  gather_facts: false
  vars:
    ntp_state: >-
      {{ 'deleted' if not services.ntp.enabled | default(false) else 'merged' }}

  tasks:
    - name: Configure NTP Source Interface
      # <TODO> - Use an Ansible module to configure NTP
        config:
          source: # <TODO> - Use a variable to specify the source interface
        state: # <TODO> - Use a play variable to define the NTP state
      when: services.ntp.source # <TODO> - Use a filter to set a default value

    - name: Configure NTP Servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: # <TODO> - Use a variable and a filter for the NTP servers
        state: "{{ ntp_state }}"
      loop: "{{ ntp.servers }}"  # <TODO> - Use a filter to set a default value

    - name: Configure NTP Peers
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: # <TODO> - Use a variable to define the peer
        state: "{{ ntp_state }}"
      loop: "{{ ntp.peers }}"  # <TODO> - Use a filter to set a default value
      loop_control:
        loop_var: current_peer
        label: "Configuring peer '{{ current_peer }}'"
