---
- name: Configure LLDP
  hosts: all_routers
  gather_facts: false
  vars:
    lldp_state: |-
      {{ 'deleted' if not services.lldp.enabled | default(false) else 'merged' }}

  tasks:
    - name: Enable LLDP Service
      cisco.ios.ios_lldp_global:
        # <TODO> - Specify LLDP global parameters
        state: # <TODO> - Use a variable to define the desired state

    - name: Enable LLDP on interfaces
      cisco.ios.ios_lldp_interfaces:
        config:
          - name: # <TODO> - Use a variable to specify the interface name
            receive: # <TODO> - Specify interface LLDP rx state
            transmit: # <TODO> - Specify interface LLDP tx state
        state: "{{ interface_lldp_state }}"
      loop: "{{ host_interfaces }}"
      loop_control:
        label: "{{ interface_dict.key }}"
      vars:
        interface_dict: "{{ lookup('ansible.builtin.dict', item) }}"
        interface_lldp_state: # <TODO> - Create a task variable to define the state
