---
services:
  restconf:
    enabled: true
  ntp:
    source: Loopback0
    # <TODO> - Set NTP State
  netconf:
    enabled: true
    features:
      - "candidate-datastore"
      - "side-effect-sync"
  lldp:
    enabled: true
